# Use the officiel PHP image with Apache
FROM php:8.2-apache

# Install MySQL extensions for PHP (essential for connecting to the database)
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Define a build argument with a default value
ARG APP_SOURCE=./app

# Copy the source code from the 'app' directory to the Apache root
COPY ${APP_SOURCE}/ /var/www/html/

# Port 80 is the default port for HTTP traffic
EXPOSE 80