# Use the officiel Apache image based on Alpine Linux
FROM httpd:alpine

# Define a build argument with a default value
ARG APP_SOURCE=./app

# Copy the source code from the 'app' directory to the Apache root
COPY ${APP_SOURCE}/ usr/local/apache2/htdocs/

# Port 80 is the default port for HTTP traffic
EXPOSE 80