services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PATH=${APP_PATH}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    restart: always